# Generated by Django 5.1.6 on 2025-03-03 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('description', models.TextField(verbose_name='Descripción de la tarea')),
                ('state', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TO DO', 'To Do'), ('DOING', 'Doing'), ('TEST', 'Test'), ('DONE', 'Done')], default='BACKLOG', max_length=10, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5, verbose_name='Prioridad')),
                ('due_date', models.DateField(verbose_name='Fecha de entrega')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['due_date', 'priority'],
            },
        ),
    ]
