# Generated by Django 5.1.6 on 2025-03-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0001_initial'),
    ]

    operations = [
    ]
