# Generated by Django 5.1.6 on 2025-04-07 20:31

from django.db import migrations

def populate_initial_state_and_priority(apps, schema_editor):
    State = apps.get_model("app_tareas", "State")
    Priority = apps.get_model("app_tareas", "Priority")

    states = [
        ("BACKLOG", "Backlog"),
        ("TO DO", "To Do"),
        ("DOING", "Doing"),
        ("TEST", "Test"),
        ("DONE", "Done"),
    ]

    priorities = [
        ("ALTA", "Alta"),
        ("MEDIA", "Media"),
        ("BAJA", "Baja"),
    ]

    for code, name in states:
        State.objects.get_or_create(code=code, defaults={"name": name})

    for code, name in priorities:
        Priority.objects.get_or_create(code=code, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ("app_tareas", "0001_initial"), 
    ]

    operations = [
        migrations.RunPython(populate_initial_state_and_priority),
    ]
